In [ ]:
import numpy as np
# 200x400
file1 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140025.npy"
file2 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140025.dat"

# 200x200
file1 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140343.npy"
file2 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140343.dat"

# raster 400x400
file1 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140705.npy"
file2 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-140705.dat"

# aim 1500x500
file1 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-141111.npy"
file2 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-141111.dat"

# galvo
file1 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-142356.npy"
file2 = "C:/Users/User/AppData/Local/2026-06-18/2026-06-18-142356.dat"


d1=np.load(file1).squeeze()
d2=np.load(file2)
print("d1: " + str(np.shape(d1)))    
print("d2: " + str(np.shape(d2)))
if np.shape(d1)==np.shape(d2):
    print("shapes match")
else:
    print("SHAPES DO NOT MATCH")
 
nonzero_bscans = np.any(d1, axis=(1,2))
nonzero_bscan_indices = np.argwhere(nonzero_bscans == True)
print("file1 has {:d} nonzero_bscan_indices".format(len(nonzero_bscan_indices)))
print(nonzero_bscan_indices)

nonzero_bscans = np.any(d2, axis=(1,2))
nonzero_bscan_indices = np.argwhere(nonzero_bscans == True)
print("file2 has {:d} nonzero_bscan_indices".format(len(nonzero_bscan_indices)))
#print(nonzero_bscan_indices)


d1: (500, 500, 1024)
d2: (500, 500, 1024)
shapes match
file1 has 5 nonzero_bscan_indices
[[495]
 [496]
 [497]
 [498]
 [499]]
file2 has 500 nonzero_bscan_indices


In [45]:

dd=d1[495,:,:]
print("single bscan shape " + str(np.shape(dd)))
nonzero_ascans = np.any(dd, axis=1)
print("bscan 495 has {:d} nonzero ascans".format(np.sum(nonzero_ascans)))

# # pick the last ascan, dd[399,:] and compare it to ascans in d2[199,:,:]
# s199 = np.sum(dd[399,:])
# print(s199)
# s2=np.sum(d2, axis=2)
# print(str(np.shape(s2)))
# print("any equal? " + str(np.where(s2==s199)))

single bscan shape (500, 1024)
bscan 495 has 61 nonzero ascans


In [16]:
print(d1[199,0,:])
print(np.shape(dd))
np.any(dd, axis=1)

[0 0 0 ... 0 0 0]
(400, 1024)


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
# Compare all individual ascans in d2 with 

print(np.sum(d11[199,499]==d2[199,499]))


56
